# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: codefreshio/microci
  tag: latest
  pullPolicy: Always
service:
  name: microci
  type: NodePort
  externalPort: 9000
  internalPort: 9000
  slackChannel: "pumba"
secret:
  githubWebhookSecret: "Z2FpYS1naXRodWItc2VjcmV0"
  slackApiKey: "eG94cC00NzM5NTE2OTc1LTQ3Mzk1MTY5OTEtNDQ3Nzk2NTQ2NjMtMGQ2MDFmMjlkMw=="
ingress:
  enabled: true
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - chart-dev.local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/redirect-to-https: "false"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources:
  limits:
    cpu: 500m
    memory: 1024M
  requests:
    cpu: 200m
    memory: 256M

